#!/usr/bin/env python3
"""Materialize the D8 GeoJSON fixture set (reader edge cases and
RFC7946 writer probes) into the target directory."""
import base64, os, sys

FILES = {
    'am4326.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"n":1},"geometry":{"type":"LineString","coordinates":[[178.5,52.0],[-179.5,52.5]]}}]}\n',
    'amlat.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[10,95]}}]}\n',
    'amln2.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[185,10],[190,12]]}}]}\n',
    'amln3.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiLineString","coordinates":[[[178.5,52.0],[-179.5,52.5]],[[1,2],[3,4]]]}}]}\n',
    'ampoly.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[178,50],[-178,50],[-178,54],[178,54],[178,50]]]}}]}\n',
    'ampt.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[190.5,10]}},{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[-200,-5]}}]}\n',
    'b1.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[1.5,2.5,3.5,4.5]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[0,0],[5,5]]}}]}\n',
    'b_a1.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[169,0],[-100,5]]}}]}',
    'b_a2.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[100,0],[-169,5]]}}]}',
    'b_a3.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[169,0],[-135,5]]}}]}',
    'b_m1.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[169,0],[175,3],[-169,5]]}}]}',
    'b_m2.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[150,0],[-169,5]]}}]}',
    'b_mix1.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[169,0],[-110,5]]}}]}',
    'b_mix2.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[110,0],[-169,5]]}}]}',
    'b_mp160.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[10,10],[170,20]]}}]}',
    'b_mp181.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[-91,0],[91,5]]}}]}',
    'b_mp200.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[-100,0],[100,5]]}}]}',
    'b_mp3.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[10,0],[170,5],[-170,8]]}}]}',
    'b_mpA.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[169,0],[-169,5]]}}]}',
    'b_mpB.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[171,0],[-171,5]]}}]}',
    'b_mpC.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[170,0],[-171,5]]}}]}',
    'b_mpD.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[170,10],[-170,20]]}}]}',
    'b_mpE.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[171,0],[178,5],[-171,8]]}}]}',
    'b_mpF.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[171,0],[175,5]]}}]}',
    'b_s120.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[120,0],[-120,5]]}}]}',
    'b_s135.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[135,0],[-135,5]]}}]}',
    'b_s150.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[150,0],[-150,5]]}}]}',
    'b_s160.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[160,0],[-160,5]]}}]}',
    'b_s165.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[165,0],[-165,5]]}}]}',
    'b_single.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[170,10],[180,12]]}}]}',
    'b_t1001.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[100.1,0],[-100.1,5]]}}]}',
    'b_t101.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[101,0],[-101,5]]}}]}',
    'b_t105.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[105,0],[-105,5]]}}]}',
    'b_t110.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[110,0],[-110,5]]}}]}',
    'b_t115.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[115,0],[-115,5]]}}]}',
    'b_t119.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[119,0],[-119,5]]}}]}',
    'b_t1195.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[119.5,0],[-119.5,5]]}}]}',
    'b_t11999.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[119.99,0],[-119.99,5]]}}]}',
    'bad.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"a":1},TRUNC\n',
    'bb.json': '{"type":"FeatureCollection","bbox":[0,0,100,100],"features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[5,6]}}]}\n',
    'c1.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[5,5,2,9],[0,0]]}}]}\n',
    'cp2.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"n":2},"geometry":{"type":"Point","coordinates":[20,30]}},{"type":"Feature","properties":{"n":1},"geometry":{"type":"Polygon","coordinates":[[[178,50],[-178,50],[-178,54],[178,54],[178,50]]]}}]}\n',
    'd1.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[7,8,9]}},{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[1.5,2.5,3.5,4.5]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[0,0],[5,5]]}}]}\n',
    'd23.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[10,20]}},{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[1,2,3]}}]}\n',
    'e1.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[0,0],[5,5]]}},{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[1.5,2.5,3.5,4.5]}}]}\n',
    'empty.json': '{"type":"FeatureCollection","features":[]}\n',
    'emptyg.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"GeometryCollection","geometries":[]}}]}\n',
    'f1.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[0,0],[5,5,2,9]]}},{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[1.5,2.5,3.5,4.5]}}]}\n',
    'f2.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[178.5,52.0],[-179.5,52.5]]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[177,10],[-177,11]]}}]}\n',
    'f3.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[178.5,52.0],[-179.5,52.5]]}},{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[10,20]}}]}\n',
    'fid.json': '{"type":"FeatureCollection","features":[{"type":"Feature","id":5,"properties":{"a":1},"geometry":{"type":"Point","coordinates":[1,2]}}]}\n',
    'g1f.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[7,8,9]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[0,0],[5,5,2,9]]}}]}\n',
    'gc4.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"GeometryCollection","geometries":[{"type":"Point","coordinates":[1,2,3,4]},{"type":"Point","coordinates":[9,8]}]}}]}\n',
    'gcb.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"GeometryCollection","geometries":[{"type":"Point","coordinates":[169,0]},{"type":"Point","coordinates":[-169,5]}]}}]}',
    'gcm.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"GeometryCollection","geometries":[{"type":"Point","coordinates":[1,2]},{"type":"Point","coordinates":[3,4,5]}]}}]}\n',
    'h1.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[7,8]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[0,0],[5,5,2,9]]}}]}\n',
    'l4.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[0,0],[1,1,2,3]]}}]}\n',
    'l43.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[0,0,1],[5,5,2,9]]}}]}\n',
    'md.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[1,2,3],[4,5,6]]}},{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[10,20]}}]}\n',
    'mls.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiLineString","coordinates":[[[0,0],[1,1]],[[2,2,5],[3,3,6]]]}}]}\n',
    'mls1.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiLineString","coordinates":[[[178.5,52.0],[-179.5,52.5]]]}}]}',
    'mp2z.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[1,2],[3,4,5]]}}]}\n',
    'mp4.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[1,2,3,4],[9,8]]}}]}\n',
    'mpoly.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPolygon","coordinates":[[[[0,0],[0,1],[1,1],[0,0]]],[[[2,2,9],[2,3,9],[3,3,9],[2,2,9]]]]}}]}\n',
    'nullg.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"a":1},"geometry":null}]}\n',
    'p23.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[1,2]}},{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[9,8,7]}}]}\n',
    'p24.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[1,2]}},{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[9,8,7,6]}}]}\n',
    'p3.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"a":1},"geometry":{"type":"Point","coordinates":[1.5,2.5,3.5]}}]}\n',
    'p34.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[9,8,7]}},{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[1.5,2.5,3.5,4.5]}}]}\n',
    'p3d.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[1,2,3]}}]}',
    'p4.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"a":1},"geometry":{"type":"Point","coordinates":[1.5,2.5,3.5,4.5]}}]}\n',
    'p42bbox.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[1.5,2.5,3.5,4.5]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[0,0],[5,5,2,9]]}}]}\n',
    'p43.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"a":1},"geometry":{"type":"Point","coordinates":[1.5,2.5,3.5,4.5]}},{"type":"Feature","properties":{"a":2},"geometry":{"type":"Point","coordinates":[9,8,7]}}]}\n',
    'p44.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"a":1},"geometry":{"type":"Point","coordinates":[1.5,2.5,3.5,4.5]}},{"type":"Feature","properties":{"a":2},"geometry":{"type":"Point","coordinates":[9,8,7,6]}}]}\n',
    'pc.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"n":1},"geometry":{"type":"Polygon","coordinates":[[[178,50],[-178,50],[-178,54],[178,54],[178,50]]]}},{"type":"Feature","properties":{"n":2},"geometry":{"type":"Point","coordinates":[20,30]}}]}\n',
    'q1.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[0,0],[5,5,2,9]]}},{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[7,8,9]}}]}\n',
    'q2.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"GeometryCollection","geometries":[{"type":"Point","coordinates":[7,8]}]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[0,0],[5,5,2,9]]}}]}\n',
    'q3.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[7,8]]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[0,0],[5,5,2,9]]}}]}\n',
    'q4.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[7,8]}},{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[1.5,2.5,3.5,4.5]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[0,0],[5,5,2,9]]}}]}\n',
    'r1.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[0,0],[5,5,2,9]]}},{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[7,8]]}}]}\n',
    'r2.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[1.5,2.5,3.5,4.5]}},{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[7,8]]}}]}\n',
    'r3.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[0,0],[5,5]]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[1,1],[5,5,2,9]]}}]}\n',
    'r4.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[1,1],[5,5,2,9]]}},{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[0,0],[5,5]]}}]}\n',
    'src4326.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"n":1},"geometry":{"type":"Point","coordinates":[3.1,46.2]}},{"type":"Feature","properties":{"n":2},"geometry":{"type":"LineString","coordinates":[[3.0,46.0],[3.05,46.05]]}}]}\n',
    't_a.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"a":1},TRUC',
    't_b.json': '{"type":"FeatureCollection","features":[{Q',
    't_c.json': '{"type":"FeatureCollection","features":[{"type" Q',
    't_d.json': '{"type":"FeatureCollection","features":[{"type":Q',
    't_e.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"a":1}Q',
    't_f.json': '{"type":"FeatureCollection","features":[{"type":"Feature"} T',
    't_g.json': '{"type":"FeatureCollection","features":[T',
    't_h.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"a":1,T',
    't_i.json': '{"type":"FeatureCollection",T',
    't_j.json': '{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Point",T',
    't_k.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":null},T',
    't_l.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"a":1,5',
    't_m.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"a":1,{',
    't_m2.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"a":1,{',
    't_n.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"a":1,[',
    't_o2.json': '{"type":"FeatureCollection","features":[{"a":1,t',
    't_p2.json': '{"type":"FeatureCollection","features":[{5',
    't_q2.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{5',
    't_r2.json': '{"type":"FeatureCollection","features":[{t',
    'two.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"n":1},"geometry":{"type":"Point","coordinates":[10,95]}},{"type":"Feature","properties":{"n":2},"geometry":{"type":"Point","coordinates":[20,30]}}]}\n',
    'two2.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"n":2},"geometry":{"type":"Point","coordinates":[20,30]}},{"type":"Feature","properties":{"n":1},"geometry":{"type":"Point","coordinates":[10,95]}}]}\n',
    'w_crosspoly2.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[175,10],[-175,10],[-175,20],[175,20],[175,10]]]}}]}',
    'w_dedup2.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[178,10],[180,11],[-179,13]]}}]}',
    'w_gcln.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"GeometryCollection","geometries":[{"type":"LineString","coordinates":[[178.5,52.0],[-179.5,52.5]]},{"type":"Point","coordinates":[190.5,10]}]}}]}',
    'w_ln180v.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[178,10],[180,11],[-179,12]]}}]}',
    'w_ln361.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[361,10],[365,12]]}}]}',
    'w_lnneg.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[-185,10],[-190,12]]}}]}',
    'w_mirror.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[179,10],[-180,11],[178,12]]}}]}',
    'w_mpt.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[190.5,10],[-200,-5],[20,30]]}}]}',
    'w_negmix.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[-181,10],[-179,12]]}}]}',
    'w_poly185.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[185,50],[190,50],[190,54],[185,54],[185,50]]]}}]}',
    'w_polymix.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[179,50],[181,50],[181,54],[179,54],[179,50]]]}}]}',
    'w_pt180.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[180,10]}}]}',
    'w_pt550.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[550,10]}}]}',
    'w_ptm180.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[-180,10]}}]}',
    'w_ptneg550.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[-550,10]}}]}',
    'w_rev180.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[-179,10],[-180,11],[179,12]]}}]}',
    'w_spec.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[-179,10],[180,11],[-178,12]]}}]}',
    'w_specno.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[-179,10],[180,11],[178,12]]}}]}',
    'w_v2.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[178,10],[-180,11],[-179,12]]}}]}',
    'w_v3.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[179,10],[-179,12],[178,14],[-178,16]]}}]}',
    'w_v4.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[-179.5,52.5],[178.5,52.0]]}}]}',
    'w_v5.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[178,10],[180,11]]}}]}',
    'w_v6.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[181,10],[179,12]]}}]}',
    'w_wideline.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[-179,10],[0,12],[179,14]]}}]}',
    'w_widepoly.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[-179,10],[0,10],[179,10],[179,20],[0,20],[-179,20],[-179,10]]]}}]}',
    'w_z3d.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[178.5,52,100],[-179.5,52.5,200]]}}]}',
    'x1.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[180,10],[185,12]]}}]}',
    'x10.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPoint","coordinates":[[550,10],[-550,20]]}}]}',
    'x2.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[-185,10],[-180,12]]}}]}',
    'x3.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[190,10],[360,12]]}}]}',
    'x4.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[190,10],[360.5,12]]}}]}',
    'x5.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"GeometryCollection","geometries":[{"type":"Polygon","coordinates":[[[178,50],[-178,50],[-178,54],[178,54],[178,50]]]},{"type":"Polygon","coordinates":[[[179,10],[-179,10],[-179,20],[179,20],[179,10]]]}]}}]}',
    'x6.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[]}}]}',
    'x7.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"GeometryCollection","geometries":[]}}]}',
    'x8.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiPolygon","coordinates":[[[[178,50],[-178,50],[-178,54],[178,54],[178,50]]],[[[10,10],[11,10],[11,11],[10,10]]]]}}]}',
    'x9.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"MultiLineString","coordinates":[[[178.5,52,100],[-179.5,52.5,200]]]}}]}',
    'z2.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"LineString","coordinates":[[1,2,3],[4,5,6]]}}]}',
    'z3.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[1,2,5]}},{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[3,4,50]}},{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[6,7]}}]}\n',
    'z4.json': '{"type":"FeatureCollection","features":[{"type":"Feature","properties":{}},{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[3,4,50]}}]}\n',
}

B64 = {
    'am/a.dbf': 'A34HHAEAAABBAAoAAAAAAAAAAAAAAAAAAAAAAABXAABuAAAAAAAAAAAAAE4AAAAACQAAAAAAAAAAAAAAAAAAAA0gICAgICAgICAxGg==',
    'am/a.prj': 'UFJPSkNTWyJXR1NfMTk4NF9VVE1fWm9uZV82ME4iLEdFT0dDU1siR0NTX1dHU18xOTg0IixEQVRVTVsiRF9XR1NfMTk4NCIsU1BIRVJPSURbIldHU18xOTg0Iiw2Mzc4MTM3LjAsMjk4LjI1NzIyMzU2M11dLFBSSU1FTVsiR3JlZW53aWNoIiwwLjBdLFVOSVRbIkRlZ3JlZSIsMC4wMTc0NTMyOTI1MTk5NDMzXV0sUFJPSkVDVElPTlsiVHJhbnN2ZXJzZV9NZXJjYXRvciJdLFBBUkFNRVRFUlsiRmFsc2VfRWFzdGluZyIsNTAwMDAwLjBdLFBBUkFNRVRFUlsiRmFsc2VfTm9ydGhpbmciLDAuMF0sUEFSQU1FVEVSWyJDZW50cmFsX01lcmlkaWFuIiwxNzcuMF0sUEFSQU1FVEVSWyJTY2FsZV9GYWN0b3IiLDAuOTk5Nl0sUEFSQU1FVEVSWyJMYXRpdHVkZV9PZl9PcmlnaW4iLDAuMF0sVU5JVFsiTWV0ZXIiLDEuMF1d',
    'am/a.shp': 'AAAnCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXugDAAADAAAACEWe9rlmIkHFB1gfDftVQY2U1hghgiZBw+GE2vI1VkEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAoAwAAAAhFnva5ZiJBxQdYHw37VUGNlNYYIYImQcPhhNryNVZBAQAAAAIAAAAAAAAACEWe9rlmIkHFB1gfDftVQY2U1hghgiZBw+GE2vI1VkE=',
    'am/a.shx': 'AAAnCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANugDAAADAAAACEWe9rlmIkHFB1gfDftVQY2U1hghgiZBw+GE2vI1VkEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADIAAAAo',
}


def main():
    d = sys.argv[1] if len(sys.argv) > 1 else "."
    for name, content in FILES.items():
        with open(os.path.join(d, name), "w") as f:
            f.write(content)
    os.makedirs(os.path.join(d, "am"), exist_ok=True)
    for name, content in B64.items():
        with open(os.path.join(d, name), "wb") as f:
            f.write(base64.b64decode(content))


if __name__ == "__main__":
    main()
