#include "engine.h"

void registerVsiHandlers();
void registerVsiSozipHandlers();
void registerRasterHandlers();
void registerRasterCreateHandler();
void registerRasterConvertHandler();
void registerDatasetHandlers();
void registerDriverHandlers();
void registerRasterEditHandlers();
void registerVectorHandlers();
void registerVectorConvertHandler();
void registerVectorCreateHandler();
void registerVectorReprojectHandler();
void registerVectorGeosHandlers();
void registerVectorSqlVerbHandlers();
void registerVectorGeomVerbHandlers();
void registerVectorClipHandler();
void registerVectorCombineHandler();
void registerVectorSetFieldTypeHandler();
void registerVectorUpdateHandler();
void registerVectorIndexHandlers();
void registerVectorGridHandlers();
void registerRasterSelectHandler();
void registerRasterTailHandlers();
void registerRasterStubHandlers();
void registerRasterCalcHandlers();
void registerRasterPxHandlers();
void registerRasterColorHandlers();
void registerRasterCompareHandler();
void registerPipelineHandlers();
void registerMdimHandlers();
void registerRasterPixelInfoHandlers();
void registerRasterContourHandler();
void registerRasterStackHandler();
void registerRasterUpdateHandler();
void registerRasterMosaicHandler();
void registerRasterFootprintHandler();
void registerRasterTileHandler();
void registerRasterIndexHandler();
void registerRasterPolygonizeHandler();
void registerRasterResizeHandler();
void registerRasterViewshedHandler();
void registerRasterAsFeaturesHandler();
void registerRasterCleanCollarHandler();
void registerRasterZonalStatsHandler();
void registerRasterBlendHandler();
void registerRasterPansharpenHandler();
void registerRasterRasterizeHandler();

void registerAllHandlers()
{
    registerVsiHandlers();
    registerVsiSozipHandlers();
    registerRasterHandlers();
    registerRasterCreateHandler();
    registerRasterConvertHandler();
    registerDatasetHandlers();
    registerDriverHandlers();
    registerRasterEditHandlers();
    registerVectorHandlers();
    registerVectorConvertHandler();
    registerVectorCreateHandler();
    registerVectorReprojectHandler();
    registerVectorGeosHandlers();
    registerVectorSqlVerbHandlers();
    registerVectorGeomVerbHandlers();
    registerVectorClipHandler();
    registerVectorCombineHandler();
    registerVectorSetFieldTypeHandler();
    registerVectorUpdateHandler();
    registerVectorIndexHandlers();
    registerVectorGridHandlers();
    registerRasterSelectHandler();
    registerRasterTailHandlers();
    registerRasterStubHandlers();
    registerRasterCalcHandlers();
    registerRasterPxHandlers();
    registerRasterColorHandlers();
    registerRasterCompareHandler();
    registerPipelineHandlers();
    registerMdimHandlers();
    registerRasterPixelInfoHandlers();
    registerRasterContourHandler();
    registerRasterStackHandler();
    registerRasterUpdateHandler();
    registerRasterMosaicHandler();
    registerRasterFootprintHandler();
    registerRasterTileHandler();
    registerRasterIndexHandler();
    registerRasterPolygonizeHandler();
    registerRasterResizeHandler();
    registerRasterViewshedHandler();
    registerRasterAsFeaturesHandler();
    registerRasterCleanCollarHandler();
    registerRasterZonalStatsHandler();
    registerRasterBlendHandler();
    registerRasterPansharpenHandler();
    registerRasterRasterizeHandler();
}
